### ISSUE TITLE
improve README: extend list in de/sciss/synth/UGenSpec.scala when adding ugen xml spec

### ISSUE THREAD

**Issue by toreller** [Sciss/ScalaColliderUGens#58]
I think the UGen needs to be registered in the list in order to build it. This could be mentioned in the tutorial

**Comment by Sciss** [comment]
You mean you want to add new UGen specifications to be compiled, right? Let me know if any are missing. Yes, the sbt projects runs the source file generator based on the list in UGenSpec, but you could also add another sub-project for a particular sc3-plugin, running the generator with a custom xml file

**Comment by Sciss** [comment]
You see here the switch `--standard` for the core project:

https://github.com/Sciss/ScalaColliderUGens/blob/69cc32c814669ac9ece33f1cf00b19f7806b748e/build.sbt#L119

Instead, you could also just pass the xml file path to the `Gen` program:

https://github.com/Sciss/ScalaColliderUGens/blob/master/gen/src/main/scala/de/sciss/synth/ugen/Gen.scala#L54

As a note to self, this should be facilitated by `runUGenGenerator` in the build script directly.

**Comment by toreller** [comment]
thanks for the clarification. You got my pull request, right? 

Initially I wanted to generate the scala source file by issuing the gen command manually. It indeed generated it, but I did not find a way to compile it to class file other than registering the UGen name in de/sciss/synth/UGenSpec.scala. And as it is a standard plugin UGen, I thought its best to build it like the other such UGens like DMF1. So thought it is a good idea to document it in the readme (not that much important though)

**Comment by Sciss** [comment]
Everything that's in sc3-plugins is fine in the 'plugins' project, so adding MDA to `thirdPartyPlugins` is absolutely correct. Thank you; please have a look at the review, there are a few issues with the documentation, and you need to base the pull request against the 'work' branch.

**Comment by toreller** [comment]
ok, thanks for the review. I took over all the info I could find in the original docs http://doc.sccode.org/Classes/MdaPiano.html, not sure if I can answer all your questions in the review. But I will try, I come back to this tomorrow!

**Comment by Sciss** [comment]
Ok, thanks. If there is no documentation for parameters of the original plugin, and you cannot infer them, then of course you can do little; just try to be as specific as possible with the parameters, in order to have all the docs in coherent style. Thanks!

**Comment by toreller** [comment]
Jo, will do!!
